services:
  - type: web
    name: evolution-api-datacrazy
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: SERVER_URL
        sync: false
      - key: AUTHENTICATION_TYPE
        value: apikey
      - key: AUTHENTICATION_API_KEY
        generateValue: true
      - key: AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES
        value: "true"
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_CONNECTION_URI
        sync: false
      - key: DATABASE_CONNECTION_CLIENT_NAME
        value: evolution_api
      - key: DATABASE_SAVE_DATA_INSTANCE
        value: "true"
      - key: DATABASE_SAVE_DATA_NEW_MESSAGE
        value: "true"
      - key: DATABASE_SAVE_MESSAGE_UPDATE
        value: "true"
      - key: DATABASE_SAVE_DATA_CONTACTS
        value: "true"
      - key: DATABASE_SAVE_DATA_CHATS
        value: "true"
      - key: DATABASE_SAVE_DATA_LABELS
        value: "true"
      - key: DATABASE_SAVE_DATA_HISTORIC
        value: "true"
      - key: CACHE_REDIS_ENABLED
        value: "false"
      - key: CACHE_LOCAL_ENABLED
        value: "true"
      - key: DEL_INSTANCE
        value: "false"
      - key: QRCODE_LIMIT
        value: "30"
      - key: WEBHOOK_GLOBAL_ENABLED
        value: "false"
      - key: CONFIG_SESSION_PHONE_CLIENT
        value: DataCrazy
      - key: CONFIG_SESSION_PHONE_NAME
        value: Chrome
      - key: LOG_LEVEL
        value: ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS
      - key: LOG_COLOR
        value: "true"
      - key: LOG_BAILEYS
        value: error
